config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", confirmations: 'users/confirmations'}
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
	resources :locations do
	  get :autocomplete_tag_name, :on => :collection
	  member do
 	 		get 'request_removal'
  	end
	end

	root 'welcome#index'

		get '/about' => 'pages#about'
		get '/contacto' => 'pages#contact', as: 'contact'
		post '/contacto' => 'pages#contact'
		get '/faq' => 'pages#faq'
		get '/terminos-y-condiciones' => 'pages#terms-and-conditions', as: 'terms_conditions'
		get '/gracias' => 'pages#thanks'
		get '/nueva_locacion' => 'pages#new_location'
		get '/signup' => 'users#new', as: 'new_session'
		post '/users/new' => 'users#create'
	  get 'request_annulation/:id' => 'users#request_annulation', as: 'user_annulation'
		get '/login' => 'sessions#new'
		post '/login' => 'sessions#create'
		get '/logout' => 'sessions#destroy'
		get '/help/password' => 'sessions#requestpasswordupdate'
		post '/help/password' => 'sessions#requestpasswordupdate'
		get '/help/updatepassword/:code' => 'sessions#updatepassword', as: 'update_password'
		post '/help/updatepassword/:code' => 'sessions#updatepassword'
	  get 'location/:id/show_modal' => 'locations#request_removal', as: 'delete_location_modal'
	  get 'location/:id/request_del' => 'locations#delete_request', as: 'location_delete'
		resources :users, except: [:index, :edit, :update] do
			collection do
				get :edit
			end
		end
		patch '/users/update' => 'users#update'
		get '/set_locale/' => 'users#set_locale'

		get 'bookings/new' => 'bookings#new'
		get 'bookings/:id/edit', to: 'bookings#edit', as: 'edit_booking'
	  post 'bookings/:id/edit', to: 'bookings#update'
		post 'bookings/price' => 'bookings#price'
		get 'bookings/:code' => 'bookings#show', as: 'booking'
		get 'bookings/:code/payment/confirm' => "bookings#confirmpayment"
		get 'bookings/:code/accept' => 'bookings#accept', as: 'booking_accept'
		get 'bookings/:code/cancel' => 'bookings#cancel', as: 'booking_cancel'
		get 'bookings/:code/delete' => 'bookings#delete'
		delete "bookings/:id" => "bookings#destroy"
		post 'bookings/:code/comment' => 'bookings#comment'
		post 'bookings/create'=> 'bookings#create'
		get "bookings" => "bookings#index"
	  get 'booking/:id/cancel_modal' => "bookings#cancel_modal", as: 'cancel_booking'
	  get 'booking/:id/cancel' => 'bookings#cancel_booking', as: 'booking_cancelled'

		get 'locations/:id/approve' => 'locations#approve', as: 'approve_location'
		get 'locations/:id/archive' => 'locations#archive'
		delete 'locations/:id/destroy' => 'locations#destroy'
		get 'locations/:id/re_send_reject_email' => 'locations#re_send_reject_email'
		post 'locations/:id/frontpage' => 'locations#frontpage'
		get 'locations/:id/show_archive_modal' => 'locations#show_archive_modal'
		get 'locations/:id/show_contact_modal' => 'locations#show_contact_modal'
		put "locations/:id/feature_image" => "locations#feature_image"
		match "upload/:location" => "attachments#create", via: [:post,:patch]
		get "attachments/:id/destroy" => "attachments#destroy"
	  get 'users/:id/delete_modal' => 'users#request_delete', as: 'delete_modal'
	  get "uploads/:id/destroy" => "uploads#destroy"

		get '/admin/' => redirect('/admin/locations')
		get '/admin/collections' => 'collections#admin'
		get '/admin/locations' => 'locations#admin'
		get '/admin/users' => 'users#admin'
		get '/admin/bookings' => 'bookings#admin'

		resources :bookings
		resources :collections
		resources :locations

	resources :confs, only: [:index] do
    collection do
      get :edit
      post :update
    end
  end

end

app/models/booking.rb
class Booking < ActiveRecord::Base
	enum status: [:archived,:waiting,:accepted,:paid]
	belongs_to :location
	belongs_to :user
	before_create :generatecode
	acts_as_paranoid

	def generatecode
		self.code=SecureRandom.hex[0..8] if self.code==nil
		self.save if self.id!=nil
		return self.code
	end

	def statusnames
		["Cancelada","Pendiente","Esperando Pago","Confirmada"]
	end

	def statusname
		return statusnames[self.read_attribute('status')]
	end

	def updateprice
		price=self.location.price*totaldays
		self.price=price
	end

	def accept
		if(self.status=="waiting")
			self.update_attribute(:status,"accepted")
			true
		else
			false
		end
	end

	def archive
		if self.status=="waiting" || self.status == 'accepted'
			self.update_attribute(:status,"archived")
			true
		else
			false
		end
	end

	def totaldays
		if self.end_time.present? && self.start_time.present?
			days=(self.end_time.to_date-self.start_time.to_date).to_i
			if days>0
				return days
			else
				return 1
			end
		else
			return 0
		end
	end

	def price_by_days
		fee = self.location.fee
		if fee.present? && totaldays != 0
			price = fee * totaldays
		else
			price = 0
		end
		price
	end

	def confirm_payment
		if(self.status=="accepted")
			self.update_attribute(:status,3)
			true
		else
			false
		end
	end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  respond_to :html, :xml, :json
  load_and_authorize_resource
  before_action :find_booking, only: [:edit]
  before_action :find_location, except: [:edit]
  skip_before_action :verify_authenticity_token

  def admin
    @bookings = Booking.all
    REDIS.set("booking_notifications_"+current_user.id.to_s,"0")
  end

  def index
    REDIS.set("booking_notifications_"+current_user.id.to_s,"0")
    @bookings=nil
    @bookings=Booking.where("status>0").order("id DESC")
    @any_accepted = @bookings.select{|b| b.status == "accepted"}.length > 0
    @any_not_waiting = @bookings.select{|b| b.status != "waiting"}.length > 0

    @user = current_user
    unless current_user.status=="admin"
      @bookings=@bookings.where(:user_id=>current_user.id)
      current_user.locations.each do |location|
        @bookings=@bookings+location.bookings.select{|booking| booking.status != 'archived'}
      end
    end
    respond_to do |format|
      format.html
      format.xml
      format.json {@bookings.to_json}
    end
  end

  def new
    @booking = Booking.new(location_id: params[:id])
    @location = Location.find(params[:id])
  end

  def price
    price=nil
    success=true
    message=nil
    start_date=nil
    end_date=nil
    begin
      start_date=Date.parse(params[:start_date])
    rescue => e
      success=false
      message="Fecha de inicio es invalida"
    end
    begin
      end_date=Date.parse(params[:end_date])
    rescue => e
      success=false
      message="Fecha de termino es invalida"
    end
    if start_date && end_date
      @booking= Booking.new(:start_time=>start_date.to_time.beginning_of_day,:end_time=>end_date.to_time.end_of_day,:location=>Location.find(params[:location_id]))
      @booking.updateprice
      price=@booking.price
    end
    render :json=>{:success=>success,:price=>price,:message=>message}
  end

  def accept
    @booking=Booking.find_by_code(params[:code])
    @booking.accept
    UserMailer.booking_accepted(@booking).deliver
    AdminMailer.admin_booking_accepted(@booking).deliver
    REDIS.lpush("booking#{@booking.code}",{:datetime=>Time.now.to_i,:text=>"Reserva aceptada por "+@booking.location.user.full_name,:action=>"accepted"}.to_json)
    redirect_to "/bookings", :notice=>"Reserva aceptada"
  end

  def cancel
    @booking=Booking.find_by_code(params[:code])
    @booking.destroy
    REDIS.lpush("booking#{@booking.code}",{:datetime=>Time.now.to_i,:text=>"Reserva cancelada por #{current_user.full_name}",:action=>"cancelled"}.to_json)
    UserMailer.booking_cancelled(@booking).deliver
    redirect_to "/bookings", :notice=>"Reserva cancelada"
  end

  def cancel_booking
    @booking= Booking.find_by(id: params[:id])
    @user = User.find_by(id: params[:user_id])
    @booking.archive
    if @booking.user.id == @user.id
      UserMailer.client_booking_cancel(@booking, params[:reject_reason]).deliver_now
      UserMailer.owner_booking_cancel(@booking, params[:reject_reason]).deliver_now
      AdminMailer.admin_booking_cancel(@booking, params[:reject_reason]).deliver_now
    else
      UserMailer.client_booking_cancel_by_owner(@booking, params[:reject_reason]).deliver_now
      UserMailer.owner_booking_cancel_by_owner(@booking, params[:reject_reason]).deliver_now
      AdminMailer.admin_booking_cancel_by_owner(@booking, params[:reject_reason]).deliver_now
    end
    REDIS.lpush("booking#{@booking.code}",{:datetime=>Time.now.to_i,:text=>"Reserva cancelada por #{current_user.full_name}",:action=>"cancelled"}.to_json)
    redirect_to bookings_path
  end

  def delete
    @booking=Booking.find_by_code(params[:code])
    @booking.destroy
    REDIS.lpush("booking#{@booking.code}",{:datetime=>Time.now.to_i,:text=>"Reserva borrada por #{current_user.full_name}",:action=>"cancelled"}.to_json)
    UserMailer.booking_cancelled(@booking).deliver
    redirect_to "/bookings", :notice=>"Reserva eliminada"
  end

  def destroy
    if @booking.destroy
      respond_to do |format|
        format.html do
          redirect_to "/admin/bookings", :notice=>"Reserva eliminada"
        end
      end
    end
  end

  def create
    @success=false
    # check dates are valid
      @start_time=DateTime.parse(params[:start_date].to_s).beginning_of_day
      @end_time=DateTime.parse(params[:end_date].to_s).end_of_day
      @location=Location.find(params[:location_id])
      # checks start date < end date
      if(@start_time<@end_time)
        if @location.has_date_range_available?(@end_time,@start_time)
          @booking=current_user.book(@location,@start_time,@end_time)
          @success=true if @booking
        else
          @message = "Lo sentimos. La locación ya está reservada para ese rango de fechas"
        end
      else
        @message="La fecha de inicio debe ser antes de la fecha de término"
      end
    if @success==true
      UserMailer.booking_requested(@booking).deliver_now
      UserMailer.booking_sent(@booking).deliver_now
      AdminMailer.admin_booking_created(@booking).deliver_now
      comment={:datetime=>Time.now.to_i,:text=>params[:comment],:user=>{:full_name=>current_user.full_name},:action=>"comment"}
      REDIS.lpush("booking#{@booking.code}",comment.to_json) if params[:comment] && params[:comment].length>0
      User.where(status: 5).each do |admin|
        admin.notify('booking')
      end
      @booking.location.user.notify("booking")
      @booking.user.notify("booking")

      flash[:notice] = "Tu solicitud de reserva fue enviada. Por favor espera durante las próximas horas hasta que sea revisada por el administrador de la locación."
      redirect_to bookings_path
    else
      redirect_to "/", flash: {notice: @message}
    end
  end

  def show
    @booking = Booking.find_by_code(params[:code])
    @history=[]
    if(REDIS.lrange("booking#{@booking.code}",0,-1))
      REDIS.lrange("booking#{@booking.code}",0,-1).each do |json|
        @history.push(JSON.parse(json))
      end
    end
  end

  def edit
    @booking = Booking.find_by(id: params[:id])
  end

  def update
    @booking = Booking.find_by(id: params[:id])
    old_start = l(@booking.start_time, format: '%d/%m/%Y')
    old_end = l(@booking.end_time, format: '%d/%m/%Y')
    start_time = params[:start_date].to_datetime
    end_time = params[:end_date].to_datetime
    if @booking.update(start_time: start_time, end_time: end_time)
      @booking.updateprice
      if @booking.status == 'accepted'
        @booking.update(status: 'waiting')
      end
      UserMailer.booking_edit(@booking).deliver_now
      UserMailer.booking_edit_request(@booking, old_start, old_end).deliver_now
      @booking.save
      flash[:notice] = 'Tu reserva fue actualizada con éxito'
      if request.xhr?
        render json: {status: :success}.to_json
      else
        redirect_to bookings_path
      end
    else
      render bookings_path
    end
  end

  def comment
    @booking=Booking.find_by_code(params[:code])
    if params[:body] && params[:body].length>0
      comment={:datetime=>Time.now.to_i,:text=>params[:body],:user=>{:full_name=>current_user.full_name},:action=>"comment"}
      REDIS.lpush("booking#{@booking.code}",comment.to_json)
      #if owner of the booking is current_user send email to location owner
      if @booking.user==current_user
        UserMailer.booking_commented(@booking,@booking.location.user,comment[:text]).deliver
      end
      if @booking.location.user==current_user
        UserMailer.booking_commented(@booking,@booking.user,comment[:text]).deliver
      end
      render :json=>{:success=>true,:comment=>comment}
    else
      render :json=>{:success=>false}
    end
  end

  def confirmpayment
    @booking=Booking.find_by_code(params[:code])
    if @booking.confirm_payment
      UserMailer.payment_confirmed(@booking).deliver
      UserMailer.payment_confirmed_owner(@booking).deliver
      AdminMailer.payment_confirmed_admin(@booking).deliver
      REDIS.lpush("booking#{@booking.code}",{:datetime=>Time.now.to_i,:text=>"Pago confirmado",:action=>"payment"}.to_json)
      @booking.user.notify("booking")
      @booking.location.user.notify("booking")

      redirect_to "/bookings", flash: {notice: "El pago de la reserva ##{@booking.code} ha sido confirmado."}
    else
      redirect_to "/bookings", flash: {notice: "Hubo un error confirmando el pago."}
    end
  end

  def cancel_modal
    @booking = Booking.find_by(id: params[:id])
  end

  private

  def save booking
    if @booking.save
        flash[:notice] = 'booking added'
        redirect_to location_booking_path(@location, @booking)
      else
        render 'new'
      end
  end

  def find_booking
    @booking = Booking.find_by_id(params[:id].to_i)
    @location = @booking.location
  end

  def find_location
    if params[:location_id]
      @location = Location.find_by_id(params[:location_id])
    end
  end

end

app/views/bookings/_booking.html.haml
%tr
	-if current_user && current_user.status=="admin"
		/ User name
		%td
			= link_to booking.location.user.full_name, '/users/'+booking.location.user.id.to_s
	/ Location code
	%td.text-center
		.bb
			%b{:style => 'font-size:12px;'}
				= t('bookings.booking_nmbr')
				%span{:style => 'display:block; font-size:15px;'}
					= "#{booking.code}"
	/ Location dates
	%td
		.bb{:style => 'padding-right: 15px;'}
			.start-date.bbb{:style => 'font-size:16px;font-weight:600;'}
				%span{:style => 'font-size:12px;font-weight:300;'}
					= t('bookings.from')
				= l(booking.start_time, format: '%d /%m /%Y')
			.start-date{:style => 'font-size:16px;font-weight:600;'}
				%span{:style => 'font-size:12px;font-weight:300;'}
					= t('bookings.until')
				= l(booking.end_time, format: '%d /%m /%Y')

	/ Location Title
	%td
		= booking.code
		%small.help-block
	/ Location dates
	%td
		.start-date
		= l(booking.start_time, format: '%d /%m /%Y')
		.start-date
		= l(booking.end_time, format: '%d /%m /%Y')

	/ Location Title
	%td
		= link_to booking.location.title, location_path(booking.location)
		%small.help-block
	/ Actions
	- if current_user.status=="admin" && (booking.status=="paid" or booking.status=="accepted")
		%td{:style => 'vertical-align:middle;'}
			- if booking.status=="accepted"
				= link_to "/bookings/#{booking.code}/payment/confirm", class: "table-pay" do
					= t('bookings.confirm')
			- else
				.table-pay
					= t('bookings.paid')
	- else
		%td
	%td
		.btn-group
			= link_to "/bookings/"+(booking.code||=booking.generatecode), :class=> "table-btn" do
				=image_tag "#{asset_path('view.svg')}", :style => "width: 60px;"
				-# %i.mdi.mdi-eye
				%p= t('bookings.go_to')
	%td
		- if booking.status=="waiting" && (can? :accept, booking)
			= link_to "/bookings/#{booking.code}/accept", :class=> "table-btn" do
				%i.mdi.mdi-check
				%p= t('bookings.approve')
		- else
			- unless current_user == booking.location.user
				= link_to edit_booking_path(booking), :class=> "table-btn" do
					=image_tag "#{asset_path('edit.svg')}", :style => "width: 60px;"
					-# %i.mdi.mdi-pencil
					%p= t('bookings.edit')
		- unless booking.status == 'paid'
			%td
				= link_to cancel_booking_path(booking), remote: true, :class=> "table-btn" do
					=image_tag "#{asset_path('delete.svg')}", :style => "width: 60px;"
					-# %i.mdi.mdi-delete
					%p= t('bookings.cancel')
		%td

app/views/bookings/_calendar.html.erb
<div id="calendar"></div>
<%# TODO:  set info of fullcalendar %>

app/views/bookings/_cancel_modal.html.haml
#cancelModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title= t('bookings.cancel')
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = form_tag(booking_cancelled_path(@booking), method: "get") do
          .form-group
            = label_tag(:reject_reason, "#{t('bookings.cancel_reason')}")
            = hidden_field_tag 'user_id', @booking.user == current_user ? current_user.id : @booking.location.user.id
            = text_area_tag 'reject_reason', nil, class: 'form-control'
          .modal-footer
            = submit_tag t('bookings.cancel'), :class=>"btn btn-danger"

app/views/bookings/_errors.html.erb
<% if @booking.errors.any? %>
  <div class="errors">
    <h3><%= pluralize(@booking.errors.count, 'error') %>
      prohibited this booking from being saved:
    </h3>
    <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/bookings/_form.html.erb
<form method="post" action="/bookings/create", remote="true">
	<input type="hidden" name="location_id" id="location-id-input" value="<%=@location.id%>">
	<div class="form-group">
		<label><%= t('bookings.from') %></label>
		<input type="date" name="start_date" id="start-date-input" class="form-control datepicker" onchange="javascript:validateBooking()">
	</div>
	<div class="form-group">
		<label><%= t('bookings.until') %></label>
		<input type="date" name="end_date" id="end-date-input" class="form-control datepicker"  onchange="javascript:validateBooking()">
	</div>
	<p class="bg-warning" style="padding: 10px" id="booking-price-dialog">
		<i class="mdi mdi-lg mdi-cash"></i>
		<%= t('bookings.price') %>
		<b>
			<span id="booking-price"></span>
		</b>
	</p>
	<input type="submit" name="" class="btn btn-success" value="Solicitar Reserva" id="booking-submit-button"/>
</form>
<script type="text/javascript">
	$(function() {
		validateBooking();
	});
	function validateBooking() {
		$("#booking-submit-button").attr("disabled",true)
		console.log("validating booking...")
		var location_id=$("#location-id-input").val()
		console.log("location id: "+location_id)
		var start_date=$('#start-date-input').val()
		console.log("start date: "+start_date)
		var end_date=$('#end-date-input').val()
		console.log("end date: "+end_date)
		$.ajax({
			url: '/bookings/price',
			type: 'POST',
			data: {start_date: start_date, end_date: end_date, location_id: location_id},
		})
		.done(function(msg) {
			console.log(msg)
			console.log("success");
			if(msg.success==true) {
				$("#booking-price-message").hide()
				$("#booking-price-dialog").show()
				$("#booking-price").html("$"+msg.price * 0.15);
				$("#booking-submit-button").attr("disabled",false)
			}
		})
		.fail(function() {
			alert("Hubo un error cotizando tu reserva. Por favor intenta mas tarde.")
			console.log("error");
		})
		.always(function() {
			console.log("complete");
		});


	}
</script>

app/views/bookings/admin.html.haml
%section.main-content
  .container
    .row
      =render 'shared/adminmenu'
      .col-md-12
        = flash_messages
        %h1
          =@bookings.count
          Reservas
        %table.table.table-striped
          %thead
            %tr
              %th Codigo
              %th Dueño
              %th Arrendatario
              %th Estado
              %th{:colspan => "3"}
          %tbody
            - @bookings.each do |booking|
              %tr
                %td= booking.code
                %td= booking.location.user.full_name
                %td= booking.user.full_name if booking.user.present?
                %td= booking.statusname
                %td= link_to 'Ver', '/bookings/'+booking.code.to_s
                %td= link_to 'Editar', edit_booking_path(booking)
                %td= link_to 'Destruir', booking, method: :delete, data: { confirm: 'Are you sure?' }
        %br/

app/views/bookings/cancel_modal.js.erb
$("#cancelModalHolder").html("<%= j raw(render 'cancel_modal') %>")
$("#cancelModal").modal()

app/views/bookings/edit.html.erb
<div class="container">
	<div class="row" style="margin-top:30px;">
		<div class="col-md-2">

		</div>
		<div class="col-md-8">
			<h3>Editar reserva <%= @location.title %></h3>

			<% unless @booking.status == 'paid' %>
				<form method="post" action="<%= edit_booking_path(@booking)%>">
					<input type="hidden" name="location_id" id="location-id-input" value="<%=@location.id%>">
					<div class="form-group">
						<label>Desde</label>
						<input type="date" name="start_date" id="start-date-input" class="form-control datepicker" onchange="javascript:validateBooking()">
					</div>
					<div class="form-group">
						<label>Hasta</label>
						<input type="date" name="end_date" id="end-date-input" class="form-control datepicker"  onchange="javascript:validateBooking()">
					</div>
					<p class="bg-warning" style="padding: 10px" id="booking-price-dialog">
						<i class="mdi mdi-lg mdi-cash"></i>
						Precio de reserva:
						<b>
							<span id="booking-price"></span>
						</b>
					</p>
					<p class="bg-warning" style="padding: 10px;display:none;" id="booking-price-message">
						<b>
							<span id="booking-message"></span>
						</b>
					</p>
					<input type="submit" name="" class="btn btn-success" value="Actualizar Reserva" id="booking-submit-button"/>
				</form>
			<% else %>
				<br>
				<p>
					No puedes editar esta reserva dado que ya la pagaste. Si necesitas igualmente hacer algún cambio, contáctate directamente con el propietario a través del historial de reserva, o contáctate con nosotros.
				</p>
				<br>
				<div style="text-align:center;">
					<div class="btn-group" style="width: 40%;">
	          <a class="btn btn-lg btn-primary btn-block" href="<%= booking_url(@booking.code)%>" style="-webkit-appearance: none;" type="button">
	            IR A LA RESERVA
	          </a>
	        </div>
					<div class="btn-group" style="width: 40%;">
	          <a class="btn btn-lg btn-primary btn-block" href="/contacto" style="-webkit-appearance: none;" type="button">
	            CONTÁCTANOS
	          </a>
	        </div>
        </div>
			<% end %>
			<script type="text/javascript">
				$(function() {
					validateBooking();
				});
				function validateBooking() {
					$("#booking-submit-button").attr("disabled",true)
					console.log("validating booking...")
					var location_id=$("#location-id-input").val()
					console.log("location id: "+location_id)
					var start_date=$('#start-date-input').val()
					console.log("start date: "+start_date)
					var end_date=$('#end-date-input').val()
					console.log("end date: "+end_date)
					$.ajax({
						url: '/bookings/price',
						type: 'POST',
						data: {start_date: start_date, end_date: end_date, location_id: location_id},
					})
					.done(function(msg) {
						console.log(msg)
						console.log("success");
						if(msg.success==true) {
							$("#booking-price-message").hide()
							$("#booking-price-dialog").show()
							$("#booking-price").html("$"+msg.price * 0.15);
							$("#booking-submit-button").attr("disabled",false)
						}
					})
					.fail(function() {
						//alert("Hubo un error cotizando tu reserva. Por favor intenta mas tarde.")
						console.log("error");
					})
					.always(function() {
						console.log("complete");
					});


				}
			</script>
		</div>
		<div class="col-md-2">

		</div>
	</div>
</div>

app/views/bookings/index.html.haml
%section.main-content
	.container
		.row
			=render 'shared/adminmenu'
			.col-md-12
				= flash_messages
				%ul.breadcrumb
					%li.breadcrumb-item
						%a{:href => "/"} Inicio
					%li.breadcrumb-item
						Reservas
		=render 'calendar'
		.table-responsive
		- if @bookings.count>0
			%table.table.bookings
				%thead
					%tr
						-if current_user && current_user.status=="admin"
							%th Usuario
						%th{:style => 'width: 110px;'}=t('bookings.booking_nmbr')
						%th{:style => 'width: 180px;'}=t('bookings.date')
						%th=t('bookings.title')
						%th{:style => 'width: 150px;max-width: 150px;min-width: 150px;'}
						%th{:style => 'width: 100px;max-width: 100px;min-width: 100px;'}
						%th{:style => 'width: 70px;max-width: 70px;min-width: 70px;'}
						%th{:style => 'width: 70px;max-width: 70px;min-width: 70px;'}
				=render @bookings
		- else
			%h2
				No has hecho una reserva
			%p
				Busca en AtLocs y encuentra tu proxima locación para filmar.
			%a.btn.btn-info{:href=>"/locations"}
				Revisa locaciones

#cancelModalHolder

app/views/bookings/new.html.haml
.container
	.col-md-8.offset-md-2
		.booking-request-form.pt-4
			%h2.my-4
				=t('bookings.new')
				%strong= @location.title
			%p=t('bookings.date_select')
			= render 'form'
		- if flash[:notice]
			#success-msg.alert.alert-success
				=t('bookings.success')
				%a{:href => "/bookings"}=t('bookings.my_bookings')
		- if flash[:error]
			#error-msg.alert.alert-warning
				= flash[:error]