config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", confirmations: 'users/confirmations'}
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
	resources :locations do
	  get :autocomplete_tag_name, :on => :collection
	  member do
 	 		get 'request_removal'
  	end
	end

	root 'welcome#index'

		get '/about' => 'pages#about'
		get '/contacto' => 'pages#contact', as: 'contact'
		post '/contacto' => 'pages#contact'
		get '/faq' => 'pages#faq'
		get '/terminos-y-condiciones' => 'pages#terms-and-conditions', as: 'terms_conditions'
		get '/gracias' => 'pages#thanks'
		get '/nueva_locacion' => 'pages#new_location'
		get '/signup' => 'users#new', as: 'new_session'
		post '/users/new' => 'users#create'
	  get 'request_annulation/:id' => 'users#request_annulation', as: 'user_annulation'
		get '/login' => 'sessions#new'
		post '/login' => 'sessions#create'
		get '/logout' => 'sessions#destroy'
		get '/help/password' => 'sessions#requestpasswordupdate'
		post '/help/password' => 'sessions#requestpasswordupdate'
		get '/help/updatepassword/:code' => 'sessions#updatepassword', as: 'update_password'
		post '/help/updatepassword/:code' => 'sessions#updatepassword'
	  get 'location/:id/show_modal' => 'locations#request_removal', as: 'delete_location_modal'
	  get 'location/:id/request_del' => 'locations#delete_request', as: 'location_delete'
		resources :users, except: [:index, :edit, :update] do
			collection do
				get :edit
			end
		end
		patch '/users/update' => 'users#update'
		get '/set_locale/' => 'users#set_locale'

		get 'bookings/new' => 'bookings#new'
		get 'bookings/:id/edit', to: 'bookings#edit', as: 'edit_booking'
	  post 'bookings/:id/edit', to: 'bookings#update'
		post 'bookings/price' => 'bookings#price'
		get 'bookings/:code' => 'bookings#show', as: 'booking'
		get 'bookings/:code/payment/confirm' => "bookings#confirmpayment"
		get 'bookings/:code/accept' => 'bookings#accept', as: 'booking_accept'
		get 'bookings/:code/cancel' => 'bookings#cancel', as: 'booking_cancel'
		get 'bookings/:code/delete' => 'bookings#delete'
		delete "bookings/:id" => "bookings#destroy"
		post 'bookings/:code/comment' => 'bookings#comment'
		post 'bookings/create'=> 'bookings#create'
		get "bookings" => "bookings#index"
	  get 'booking/:id/cancel_modal' => "bookings#cancel_modal", as: 'cancel_booking'
	  get 'booking/:id/cancel' => 'bookings#cancel_booking', as: 'booking_cancelled'

		get 'locations/:id/approve' => 'locations#approve', as: 'approve_location'
		get 'locations/:id/archive' => 'locations#archive'
		delete 'locations/:id/destroy' => 'locations#destroy'
		get 'locations/:id/re_send_reject_email' => 'locations#re_send_reject_email'
		post 'locations/:id/frontpage' => 'locations#frontpage'
		get 'locations/:id/show_archive_modal' => 'locations#show_archive_modal'
		get 'locations/:id/show_contact_modal' => 'locations#show_contact_modal'
		put "locations/:id/feature_image" => "locations#feature_image"
		match "upload/:location" => "attachments#create", via: [:post,:patch]
		get "attachments/:id/destroy" => "attachments#destroy"
	  get 'users/:id/delete_modal' => 'users#request_delete', as: 'delete_modal'
	  get "uploads/:id/destroy" => "uploads#destroy"

		get '/admin/' => redirect('/admin/locations')
		get '/admin/collections' => 'collections#admin'
		get '/admin/locations' => 'locations#admin'
		get '/admin/users' => 'users#admin'
		get '/admin/bookings' => 'bookings#admin'

		resources :bookings
		resources :collections
		resources :locations

	resources :confs, only: [:index] do
    collection do
      get :edit
      post :update
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :locations, dependent: :destroy
  has_many :bookings, dependent: :destroy
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :email, uniqueness: true
  validates :password, :presence => true, :length => {:within => 6..40}, :if => :password
  validates :phone, :presence => true
  devise :confirmable, :omniauthable

  #validate :atleast_one_is_checked
  #validate_uniqueness_of: email

  enum status: [ :banned, :shadowbanned, :unverified, :verified, :moderator, :admin ]

  has_secure_password
  before_create :add_unverified_status
  before_save :set_tenant, unless: :owning || :tenant
  acts_as_paranoid

  def active_for_authentication?
    (verified? || moderator? || admin?)
  end

  def full_name
    if self.first_name && self.last_name
      self.first_name+" "+self.last_name
    elsif self.first_name
      self.first_name
    else
      self.email
    end
  end

  def claim(location)
    if(location.user_id==nil && self.id!=nil)
      location.update_attribute(:user_id,self.id)
      true
    else
      false
    end
  end

  def admin_notifications
    total = 0
    ['booking', 'location'].each do |tag|
      total += REDIS.get(tag+"_notifications_"+self.id.to_s).to_i
    end
    total
  end

  def notifications(tag)
    if REDIS.get(tag+"_notifications_"+self.id.to_s)
      REDIS.get(tag+"_notifications_"+self.id.to_s).to_i
    else
      REDIS.set(tag+"_notifications_"+self.id.to_s,"0")
      0
    end
  end

  def notify(tag)
    if REDIS.get(tag+"_notifications_"+self.id.to_s)

      REDIS.set(tag+"_notifications_"+self.id.to_s,(REDIS.get(tag+"_notifications_"+self.id.to_s).to_i+1).to_s)
    else
      REDIS.set(tag+"_notifications_"+self.id.to_s,"1")
    end
  end

  def book(location,start_time,end_time)
    if(location.status=="approved" && start_time<end_time)
      booking=Booking.new
      booking.start_time=start_time
      booking.end_time=end_time
      booking.location_id=location.id
      booking.user_id=self.id
      booking.status="waiting"
      if booking.save
        REDIS.lpush("booking#{booking.code}",{:datetime=>Time.now.to_i,:text=>"Reserva creada",:action=>"created"}.to_json)
        booking.updateprice
        booking.save

        booking
      else
        nil
      end
    else
      nil
    end
  end

  def atleast_one_is_checked
    errors.add(:base, "Selecciona al menos uno") unless owning || tenant
  end

  def self.confirm_token
		loop do
	  	token = SecureRandom.urlsafe_base64
	     break token unless User.exists?(confirmation_token: token)
		end
	end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    if user.present?
      user.update_attributes(status: 3) if !user.active_for_authentication?
      return user
    else
      registered_user = User.where(email: auth.info.email).first
      deleted_user = User.with_deleted.find_by(email: auth.info.email) unless registered_user.present?
      if registered_user.present?
        registered_user.status = 3 if !registered_user.active_for_authentication?
        registered_user.provider = auth.provider
        registered_user.uid = auth.uid
        registered_user.first_name = auth.info.first_name
        registered_user.last_name = auth.info.last_name
        registered_user.save!
        return registered_user
      elsif deleted_user.present?
        deleted_user.recover
        deleted_user.first_name = auth.info.first_name
        deleted_user.last_name = auth.info.last_name
        deleted_user.provider = auth.provider
        deleted_user.uid = auth.uid
        deleted_user.status = 3 if !deleted_user.active_for_authentication?
        deleted_user.save!
        UserMailer.welcome(deleted_user).deliver_now
        return deleted_user
      else
        User.create do |user|
          user.status = 3
          user.email = auth.info.email
          user.password = Devise.friendly_token[0,20]
          user.first_name = auth.info.first_name
          user.last_name = auth.info.last_name
          user.provider = auth.provider
          user.uid = auth.uid
          user.skip_confirmation!
          UserMailer.welcome(user).deliver_now
        end
      end
    end
  end

  def set_tenant
    self.tenant = true
  end

  private
    def add_unverified_status
      if self.provider.blank?
        self.status="unverified"
      end
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    #puts @user.email
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?

    if resource.errors.empty?
      flash[:notice] = "Cuenta confirmada, por favor inicia sesión"
      resource.update_attributes(status: 3)
      respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
    else
      respond_with_navigational(resource.errors, status: :unprocessable_entity){ render :new }
    end
  end

  # protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      session[:user_id] = @user.id
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_url
    end
  end

  def failure
    redirect_to root_path
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource :except => [:set_locale]
	skip_before_action :verify_authenticity_token

	def admin
		@users=User.all.order(id: :DESC)
	end

	def create
		@user = User.with_deleted.find_by(email: params[:user][:email])
		if @user
			@user.recover
			if @user.update(user_params)
				flash[:notice]="Gracias por reactivar tu cuenta en Atlocs! Ya puedes publicar o reservar locaciones!"
				session[:user_id] = @user.id
				#SessionMailer.confirmation_instructions(@user, @user.confirmation_token).deliver_now
				#UserMailer.confirmation(@user).deliver_now
				#UserMailer.welcome(user).deliver
				if session[:url_after_session]
					url=session[:url_after_session]
					session[:url_after_session]=nil
					redirect_to url
				else
					redirect_to root_path
				end
			else
				respond_to do |format|
					format.html {render :new}
					format.json {render json: @user.errors, success: false, message: @user.errors.full_messages.to_sentence}
				end
			end
		else
			@user=User.new(user_params)
			if @user.save
				flash[:notice]="Te has registrado en Atlocs! Te hemos enviado un email para confirmar tu registro"
				redirect_to root_path
			else
				respond_to do |format|
					format.html {render :new}
					format.json {render json: @user.errors, success: false, message: @user.errors.full_messages.to_sentence}
				end
			end
		end
	end

	def show
		if params[:id]
			@user=User.find(params[:id])
			REDIS.set("location_notifications_"+@user.id.to_s,"0") if @user == current_user
		else
			@user=current_user
		end
	end

	def edit
		@user=current_user
	end

	def update
		@user = current_user
		if @user.update_attributes(user_params)
			redirect_to "/users/#{@user.id}", :flash => :success
		else
			redirect_to "/users/edit", :flash => :error
		end
	end

	def bookings
		@user=current_user
		@bookings=@user.bookings.all
	end

	def request_delete
		@user = User.find_by(id: params[:id])
	end

	def request_annulation
		@user = User.find(params[:id])
		AdminMailer.request_destroy_admin(@user, params[:reject_reason]).deliver
		UserMailer.request_destroy(@user).deliver
		flash[:notice] = "Solicitud enviada"
		redirect_to @user
	end

	def destroy
		@user.destroy
		flash[:notice]="Usuario eliminado"
		redirect_to "/admin/users/"
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_user
	  @user = User.find(params[:id])
	end

	# Only allow a trusted parameter "white list" through.
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :phone,
																 :password, :deposit_bank, :deposit_account,
																 :password_confirmation, :owning, :tenant)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_delete_modal.html.haml
#deleteModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Anular cuenta
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = form_tag(user_annulation_path(@user), method: "get") do
          .form-group
            = label_tag(:reject_reason, "Motivo de rechazo:")
            = text_area_tag 'reject_reason', nil, class: 'form-control'
          .modal-footer
            = submit_tag 'Solicitar anulación', :class=>"btn btn-danger"

app/views/users/_location_delete_modal.html.haml
#locationModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Eliminar locación
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = form_tag(location_delete_path(@location), method: "get") do
          .form-group
            = label_tag(:reject_reason, "Motivo de rechazo:")
            = text_area_tag 'reject_reason', nil, class: 'form-control'
          .modal-footer
            = submit_tag 'Solicitar eliminación', :class=>"btn btn-danger"

app/views/users/admin.html.haml
%section.main-content
  .container
    .row
      =render 'shared/adminmenu'
      .col-md-12
        = flash_messages
        %h1
          =@users.count
          Usuarios
        %table.table.table-striped
          %thead
            %tr
              %th Nombre
              %th Fono
              %th{:colspan => "3"}
          %tbody
            - @users.each do |user|
              %tr
                %td= user.email
                %td= user.phone
                %td= link_to 'Show', '/users/'+user.id.to_s
                %td= link_to 'Edit', '/users/edit'
                %td= link_to 'Destroy', '/users/'+user.id.to_s, method: :delete, data: { confirm: 'Are you sure?' }
        %br/
        = link_to 'New user', '/signup'

app/views/users/bookings.html.erb
<h3> Bookings for <%= @user.email %></h3>
<table class="bookings_table">
  <tr>
    <th>Locacion</th>
    <th>Start</th>
    <th>End</th>
    <th>Estado</th>
    <th></th>
    <th></th>
  </tr>
  
  <% @bookings.each do |booking| %>
  <tr>
    <td><%=Location.where(:id=>booking.id).name%></td>
    <td>
      <%= booking.start_time.strftime('%e %b %Y') if booking.start_time %>
    </td>
    <td>
      al <%= booking.end_time.strftime('%e %b %Y') if booking.end_time %>
    </td>
    <td><%=booking.status%></td>
    <td><%= link_to "Delete", '#', data: { confirm: 'Are you sure?' }, method: :delete %>
    </td>
    <td><%= link_to "Edit", '#' %>
    </td>
  </tr>
  <% end %>
</table>

app/views/users/edit.html.haml
%section.main-content
  .container
    .row.padding
      = flash_messages
      .col-md-12
        %h1.text-center
          Edita tu
          %strong usuario
        %hr
        %br
        = form_for @user, url: '/users/update', html: {:class=> "form form-horizontal"} do |f|
          %fieldset
            / Form Name
            / %legend Form Name
            / Text input
            .form-group
              %label.col-md-4.control-label{:for => "textinput"} Nombre
              .col-md-4
                =f.text_field :first_name, {:class=>"textinput form-control input-md", :placeholder => "Nombre"}
            / Text input
            .form-group
              %label.col-md-4.control-label{:for => "textinput"} Apellido
              .col-md-4
                =f.text_field :last_name, {:class=>"textinput form-control input-md", :placeholder => "Apellido"}
            / Text input
            .form-group
              %label.col-md-4.control-label{:for => "textinput"} Email
              .col-md-4
                =f.text_field :email, {:class=>"textinput form-control input-md", :placeholder => "Email"}
            / Text input
            .form-group
              %label.col-md-4.control-label{:for => "textinput"} Telefono
              .col-md-4
                =f.text_field :phone, {:class=>"textinput form-control input-md", :placeholder => "Telefono", :maxlength=> "9" }
            / owning input
            .form-group
              %label.col-md-4.control-label{:for => "owninginput"} ¿Eres propietario de un inmueble?
              .col-md-4
                =f.check_box :owning, {:class=>"textinput form-control input-md"}
            / tenant input
            .form-group
              %label.col-md-4.control-label{:for => "tenantinput"} ¿Estás buscando locaciones para tu proyecto?
              .col-md-4
                =f.check_box :tenant, {:class=>"textinput form-control input-md"}


            / Password input
            .form-group
              %label.col-md-4.control-label{:for => "passwordinput"} Password
              .col-md-4
                =f.password_field :password, {:class=>"textinput form-control input-md", :placeholder => "******"}
                %span.help-block Ingresa un password solo si necesitas cambiarlo


            %h4.text-center Datos de deposito
            .form-group
              %label.col-md-4.control-label{:for => "selectinput"} Banco
              .col-md-4
                =f.select(:deposit_bank, ['Banco Santander', 'Banco Santander Banefe', 'Banco BBVA', 'Banco BICE', 'Banco Internacional', 'Banco Itaú', 'Banco de Chile / Edwards-Citi', 'Corpbanca', 'Banco Crédito e Inversiones', 'Banco del Desarrollo', 'Banco Estado', 'Banco Falabella', 'Banco Security', 'Scotiabank', 'Rabobank', 'HSBC Bank', 'Banco Ripley', 'Banco Paris', 'Banco Consorcio', 'Banco Coopeuch'], {}, { :class => 'form-control' })
            .form-group
              %label.col-md-4.control-label{:for => "textinput"} Nº de cuenta
              .col-md-4
                =f.text_field :deposit_account, {:class=>"textinput form-control input-md", :placeholder => "Número de cuenta"}


            / Button
            .form-group
              %label.col-md-4.control-label{:for => "singlebutton"}
              .col-md-4
                %button#singlebutton.btn.btn-primary{:type => "submit"} Guardar usuario

app/views/users/new.html.erb
<div class="container-fluid py-4">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 mt-3">
      <div class="card card-outline-primary card-session">
        <div class="card-header bg-primary text-white">
          <h5 class="mt-2"><%= t('user.form.title1') %></h5>
          <p class="small"><%= t('user.form.title2a') %> <strong><%= t('user.form.title2b') %></strong> <%= t('user.form.title2c') %></p>
        </div>
        <div class="card-block">
          <div class="card-form">
            <%= simple_form_for(@user, wrapper: false, label: false) do |f| %>
              <%= f.error_notification %>
              <div class="form-group">
                <label class="sr-only"><%= t('user.form.name') %></label>
                <%= f.input :first_name, input_html: { class: 'form-control' }, wrapper: false, label: false, placeholder: t('user.form.name') %>
              </div>
              <div class="form-group">
                <label class="sr-only"><%= t('user.form.last_name') %></label>
                <%= f.input :last_name, input_html: { class: 'form-control' }, wrapper: false, label: false, placeholder: t('user.form.last_name') %>
              </div>
              <div class="form-group">
                <label class="sr-only">Email</label>
                <%= f.input :email, input_html: { class: 'form-control' }, wrapper: false, label: false, placeholder: 'E-mail' %>
              </div>
              <div class="form-group">
                <label class="sr-only"><%= t('user.form.phone') %></label>
                <%= f.input :phone, input_html: { class: 'form-control' }, wrapper: false, label: false, placeholder: t('user.form.phone') %>
              </div>
              <div class="form-group">
                <label class="sr-only"><%= t('user.form.password') %></label>
                <%= f.input :password, input_html: { class: 'form-control' }, wrapper: false, label: false, placeholder: t('user.form.password') %>
              </div>
              <div class="form-group">
                <label class="sr-only"><%= t('user.form.confirm_password') %></label>
                <%= f.input :password_confirmation, input_html: { class: 'form-control' }, wrapper: false, label: false, placeholder: t('user.form.confirm_password') %>
              </div>
              <div class="form-check">
                <label class="form-check-label">
                  <%= f.input :owning, input_html: { class: 'form-check-input' }, wrapper: false, label: false, type: 'checkbox'  %>
                  <%= t('user.form.is_owning') %>
                </label>
              </div>
              <div class="form-check">
                <label class='form-check-label'>
                  <%= f.input :tenant, input_html: { class: 'form-check-input' }, wrapper: false, label: false, type: 'checkbox' %>
                  <%= t('user.form.is_tenant') %>
                </label>
              </div>

              <div class="form-actions">
                <%= f.submit "Crear Cuenta", class: "btn btn-primary btn-block" %>
              </div>
              <hr />
              <%= link_to user_facebook_omniauth_authorize_path, class: 'btn btn-block facebook-inicio' do %>
                <span><i class="mdi mdi-facebook-box mdi-lg mr-2"></i></span>
                <%= t('user.form.facebook1') %>
              <% end %>
              <p class="text-center small text-muted mt-2">
                <%= t('user.form.facebook2') %>
              </p>
            <% end %>
          </div>
      </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="p-2">
          <div class="my-2"><a href="/login"><%= t('user.form.login') %></a></div>
          <div class="my-2"><a href="/help/password"><%= t('user.form.forgot_password') %></a></div>
        </div>
      </div>
  </div>
</div>

app/views/users/request_delete.js.erb
$("#deleteModalHolder").html("<%= j raw(render 'delete_modal') %>")
$("#deleteModal").modal()

app/views/users/set_locale.js.erb
location.reload()

app/views/users/show.html.haml
%section.main-content
	.container
		= flash_messages
		.row.padding
			.col-md-8
				-if current_user && @user==current_user
					%span Iniciaste Sesión como
					%h3 #{@user.full_name}
				-if current_user && current_user.status=='admin' || current_user && @user==current_user && (can? :manage, User, user_id: current_user.id)
					%ul.user-info
						%li
							%i.mdi.mdi-lg.mdi-email
							#{@user.email}
						%li
							%i.mdi.mdi-lg.mdi-phone
							+56 #{@user.phone}
					%a.btn.btn-xs.btn-info{:href => "/users/edit"}
						%i.mdi.mdi-pencil
						Editar perfil
					= link_to 'Solicitar anulación de cuenta', delete_modal_path, :class=>"btn btn-outline-danger", :remote => true

				%hr
				%h2
					-if current_user && @user==current_user
						Mis
					%strong Locaciones
				.row.user-location-list
					- locations = current_user.status == "admin" ? @user.locations : @user.locations.where(:status=>[0,2,3])
					- locations.each do |location|
						.col-sm-6.col-md-4
							.thumbnail.thumbnail-reset.location-preview
								.image
									%span.badge.price
										%strong CLP
										= number_to_currency(location.totalprice, :unit => "$", :precision => 0)
									=link_to image_tag(location.main_attachment_url(:thumb), :class=>"collection-img"), location_path(location)
								.caption
									%span.badge.badge-danger
										= t("locations.status.#{location.status}")
									%h3.title
										= link_to location.title, location_path(location)
									%p.desc
										= location.description
									%p
										= link_to 'Editar', edit_location_path(location)
									%p
										- if current_user.status == "admin"
											= link_to 'Borrar', "/locations/#{location.id}/destroy?from_user=#{@user.id}", :method => :delete
										- else
											= link_to 'Solicitar Eliminación', delete_location_modal_path(location), :remote => true
			-if current_user && @user==current_user
				.col-md-4
					%h4 Mis Reservas
					-if @user.bookings
						%div.list-group
							-@user.bookings.each do |booking|
								%a.list-group-item{:href=>'/bookings/'+booking.code}
									%b=booking.location.title
									%br
									"#{number_to_currency(booking.price, :unit => "$", :precision => 0)} x #{booking.totaldays} día(s)"
									%span.badge
										=booking.statusname
							%li.list-group-item
								=link_to "Ver mis reservas", "/bookings"

#deleteModalHolder
#locationModalHolder