config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", confirmations: 'users/confirmations'}
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
	resources :locations do
	  get :autocomplete_tag_name, :on => :collection
	  member do
 	 		get 'request_removal'
  	end
	end

	root 'welcome#index'

		get '/about' => 'pages#about'
		get '/contacto' => 'pages#contact', as: 'contact'
		post '/contacto' => 'pages#contact'
		get '/faq' => 'pages#faq'
		get '/terminos-y-condiciones' => 'pages#terms-and-conditions', as: 'terms_conditions'
		get '/gracias' => 'pages#thanks'
		get '/nueva_locacion' => 'pages#new_location'
		get '/signup' => 'users#new', as: 'new_session'
		post '/users/new' => 'users#create'
	  get 'request_annulation/:id' => 'users#request_annulation', as: 'user_annulation'
		get '/login' => 'sessions#new'
		post '/login' => 'sessions#create'
		get '/logout' => 'sessions#destroy'
		get '/help/password' => 'sessions#requestpasswordupdate'
		post '/help/password' => 'sessions#requestpasswordupdate'
		get '/help/updatepassword/:code' => 'sessions#updatepassword', as: 'update_password'
		post '/help/updatepassword/:code' => 'sessions#updatepassword'
	  get 'location/:id/show_modal' => 'locations#request_removal', as: 'delete_location_modal'
	  get 'location/:id/request_del' => 'locations#delete_request', as: 'location_delete'
		resources :users, except: [:index, :edit, :update] do
			collection do
				get :edit
			end
		end
		patch '/users/update' => 'users#update'
		get '/set_locale/' => 'users#set_locale'

		get 'bookings/new' => 'bookings#new'
		get 'bookings/:id/edit', to: 'bookings#edit', as: 'edit_booking'
	  post 'bookings/:id/edit', to: 'bookings#update'
		post 'bookings/price' => 'bookings#price'
		get 'bookings/:code' => 'bookings#show', as: 'booking'
		get 'bookings/:code/payment/confirm' => "bookings#confirmpayment"
		get 'bookings/:code/accept' => 'bookings#accept', as: 'booking_accept'
		get 'bookings/:code/cancel' => 'bookings#cancel', as: 'booking_cancel'
		get 'bookings/:code/delete' => 'bookings#delete'
		delete "bookings/:id" => "bookings#destroy"
		post 'bookings/:code/comment' => 'bookings#comment'
		post 'bookings/create'=> 'bookings#create'
		get "bookings" => "bookings#index"
	  get 'booking/:id/cancel_modal' => "bookings#cancel_modal", as: 'cancel_booking'
	  get 'booking/:id/cancel' => 'bookings#cancel_booking', as: 'booking_cancelled'

		get 'locations/:id/approve' => 'locations#approve', as: 'approve_location'
		get 'locations/:id/archive' => 'locations#archive'
		delete 'locations/:id/destroy' => 'locations#destroy'
		get 'locations/:id/re_send_reject_email' => 'locations#re_send_reject_email'
		post 'locations/:id/frontpage' => 'locations#frontpage'
		get 'locations/:id/show_archive_modal' => 'locations#show_archive_modal'
		get 'locations/:id/show_contact_modal' => 'locations#show_contact_modal'
		put "locations/:id/feature_image" => "locations#feature_image"
		match "upload/:location" => "attachments#create", via: [:post,:patch]
		get "attachments/:id/destroy" => "attachments#destroy"
	  get 'users/:id/delete_modal' => 'users#request_delete', as: 'delete_modal'
	  get "uploads/:id/destroy" => "uploads#destroy"

		get '/admin/' => redirect('/admin/locations')
		get '/admin/collections' => 'collections#admin'
		get '/admin/locations' => 'locations#admin'
		get '/admin/users' => 'users#admin'
		get '/admin/bookings' => 'bookings#admin'

		resources :bookings
		resources :collections
		resources :locations

	resources :confs, only: [:index] do
    collection do
      get :edit
      post :update
    end
  end

end

app/views/shared/_adminmenu.html.haml
- if current_user.status == 'admin'
  .row.padding
    .main-navigation.navbar-collapse
      / start: MAIN NAVIGATION MENU
      %ul.nav.nav-pills
        %li.nav-item{}
          %a.nav-link{:href => '/admin/locations', :class => (controller.controller_name == 'locations')? 'active': ''}
            %i.mdi.mdi-lg.mdi-pin
            %span.title Locaciones
        %li.nav-item{}
          %a.nav-link{:href => '/admin/collections', :class => (controller.controller_name == 'collections')? 'active': ''}
            %i.mdi.mdi-lg.mdi-folder-image
            %span.title Colecciones
        %li.nav-item{}
          %a.nav-link{:href => '/admin/users', :class => (controller.controller_name == 'users')? 'active': ''}
            %i.mdi.mdi-lg.mdi-account
            %span.title Usuarios
        %li.nav-item{}
          %a.nav-link{:href => '/admin/bookings', :class => (controller.controller_name == 'bookings')? 'active': ''}
            %i.mdi.mdi-lg.mdi-newspaper
            %span.title Reservas
        %li.nav-item{}
          %a.nav-link{:href => '/confs/', :class => (controller.controller_name == 'confs')? 'active': ''}
            %i.mdi.mdi-lg.mdi-newspaper
            %span.title Configuraciones

app/views/shared/_breadcrumb.html.erb
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><%= link_to 'Locaciones', locations_path %></li>
    <li class="breadcrumb-item active"><%= @location.title%></li>
</ol>

app/views/shared/_footer.html.haml
%footer
	%hr
	.container.d-flex.justify-content-center
		%ul.list-inline.social-links
			%li.list-inline-item
				%a.footer-social-link{:href => "https://www.facebook.com/AtLocscom-820834398016166/", :target => "_blank"}
					%i.mdi.mdi-facebook.footer-social-icon
			%li.list-inline-item
				%a.footer-social-link{:href => "http://twitter.com/atlocs", :target => "_blank"}
					%i.mdi.mdi-twitter.footer-social-icon
			%li.list-inline-item
				%a.footer-social-link{:href => "http://instagram.com/atlocs", :target => "_blank"}
					%i.mdi.mdi-instagram.footer-social-icon

app/views/shared/_meta.html.erb
<% 
@ogtitle=@title

#TITULOS POR CATEGORIA
if @location && @location.title
	@title=@location.title+" | AtLocs"
elsif @collection && @collection.name
	@title=@collection.name+" | AtLocs"
elsif params[:s]
	@title="Resultados de locaciones para: "+params[:s]+" | AtLocs"
elsif controller.controller_name=="sessions"
	@title="Ingresa a AtLocs"
else
	@title="AtLocs - Locaciones para filmaciones, fotografía y eventos"
end 

@ogtype="website"
@ogdescription="Locaciones para filmaciones, fotografía y eventos"

if @location
	@ogdescription=@location.description
	@ogtitle=@location.title
	if @location.attachments.count>0
		@ogimage=@location.attachments.first.thumbnail(500,320)
	else 
		@ogimage=request.domain+"/location-missing.jpg"
	end
	@ogtype="article"
end

%>

<title><%=@title%></title>
<meta property="og:title" content="<%=@ogtitle%>"/>
<meta property="og:type" content="<%=@ogtype%>"/>
<meta property="og:image" content="<%=@ogimage%>"/>
<meta property="og:site_name" content="AtLocs"/>
<meta property="og:description" content="<%=@ogdescription%>"/>

app/views/shared/_navbar.html.haml
.container.navbar-wrapper
	%nav.navbar.navbar-toggleable-md.navbar-inverse.bg-primary.fixed-top
		.container
			%button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
				%span.navbar-toggler-icon
			%a.navbar-brand{:href => "/"}
				= image_tag("atlocs-logo.svg", :class=>"brand-logo", :alt=>"AtLocs")
			#navbarSupportedContent.collapse.navbar-collapse
				%ul.navbar-nav.ml-auto.mr-1
					-if current_user && current_user.status=='admin'
						%li.nav-item
							= link_to 'Admin', '/admin/', :class=>"nav-link"
							- if current_user.admin_notifications>0
								.badge
									=current_user.admin_notifications
					-unless current_user
						%li.nav-item
							%a.nav-link{:href => "/login"}
								= I18n.t('actions.log_in')
						%li.nav-item#loginlink

							%a.nav-link{:href => "/signup"}
								= I18n.t('actions.sign_up')
					-if current_user
						%li.nav-item
							= link_to(I18n.t('general.collections_and'), collections_path, :class=>"nav-link")
						%li.nav-item
							= link_to(I18n.t('general.locations'), locations_path, :class=>"nav-link")
					%li.nav-item#loginlink
						%a.nav-link{:href => "/contacto"}
							= I18n.t('general.contact')
					%li.nav-item{:style => "margin: 6px 5px;"}
						%form{ :method=>"get", :action=>"/locations/new/" }
							%input{:type=>"hidden", :name=>"newlocation", :value=>"true"}
							%button.btn.btn-secondary.text-primary.navbar-btn{ :type=>"submit"}
								%i.mdi.mdi-lg.mdi-cloud-upload
								= I18n.t('actions.publish')
					-if current_user
						%li.nav-item.dropdown.user
							%a.nav-link{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
								.user-circle
									%i.mdi.mdi-account.mdi-lg
								%i.mdi.mdi-menu-down.arrow
							%ul.dropdown-menu.dropdown-menu-right.bg-primary
								%i.mdi.mdi-menu-up.arrow
								%li
									%a{:href => "/users/"+current_user.id.to_s}
										%span
											%i.mdi.mdi-account
										= t('general.profile')
										- if current_user.notifications("location")>0
											.badge
												=current_user.notifications("location")
								%li
									%a{:href => "/users/"+current_user.id.to_s}
										%span
											%i.mdi.mdi-map-marker
										= t('general.my_locations')
										- if current_user.notifications("location")>0
											.badge
												=current_user.notifications("location")
								%li
									%a{:href => "/bookings"}
										%span
											%i.mdi.mdi-calendar-multiple
										= t('general.my_bookings')
										- if current_user.notifications("booking")>0
											.badge
												=current_user.notifications("booking")
								%li
									%a{:href => "/logout"}
										%span
											%i.mdi.mdi-close
										= t('actions.exit')
					%li.nav-item.dropdown
						%a#navbarDropdownMenuLink.nav-link{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#"}
							%i.nav-icon.mdi.mdi-help-circle
						%ul.dropdown-menu.dropdown-menu-right.bg-primary{"aria-labelledby" => "navbarDropdownMenuLink"}
							%i.mdi.mdi-menu-up.arrow
							%li
								%a{:href => "/faq"}
									FAQ
							%li
								%a{:href => "/terminos-y-condiciones"}
									=t('general.terms')
							%li
								%a{:href => "/about"}
									=t('general.about_us')
					%li.nav-item.dropdown
						%a#navbarDropdownMenuLink.nav-link{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "http://example.com"}
							.help
								= I18n.locale.to_s.upcase
						%ul.dropdown-menu.dropdown-menu-right.bg-primary{"aria-labelledby" => "navbarDropdownMenuLink"}
							%i.mdi.mdi-menu-up.arrow
							%li
								= link_to set_locale_path(locale: "es"), remote: true do
									=t('locales.spanish')
							%li
								= link_to set_locale_path(locale: "en"), remote: true do
									=t('locales.english')
				-# %form.form-inline.my-2.my-lg-0
					%input.form-control.mr-sm-2{:placeholder => "Search", :type => "text"}/
					%button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search
-# .container.navbar-wrapper
	%nav.navbar.navbar-inverse.navbar-fixed-top
		.container-fluid
			/ Brand and toggle get grouped for better mobile display
			.navbar-header
				%button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
					%span.sr-only Toggle navigation
					%span.icon-bar
					%span.icon-bar
					%span.icon-bar
				%a.navbar-brand{:href => "/"}
					= image_tag("atlocs-logo.svg", :class=>"brand-logo")
			/ Collect the nav links, forms, and other content for toggling
			#bs-example-navbar-collapse-1.collapse.navbar-collapse
				.navbar-right
					%ul.nav.navbar-nav
						- if current_user && current_user.status=='admin'
							%li
								= link_to 'Admin', '/admin/'
								- if current_user.notifications("admin")>0
									.badge
										=current_user.notifications("admin")
						-unless current_user
							%li
								%a{:href => "/login"}
									Ingresa
							%li#loginlink
								%a{:href => "/signup"}
									Regístrate

						- if current_user
							%li
								= link_to("Barrios y Colecciones", collections_path)
							%li
								= link_to("Locaciones", locations_path)
						%li.dropdown
							%a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
								Ayuda
								%span.caret
							%ul.dropdown-menu
								/ %li= link_to("Acerca de", "/about")
								%li= link_to("FAQ", "/faq")
								%li= link_to("Términos y Condiciones", "/terminos-y-condiciones")
								%li= link_to("Contacto", "/contacto")
						%li
							%form.button_to{ :method=>"get", :action=>"/locations/new/", :style=>"padding-right:10px;" }
								%input{:type=>"hidden", :name=>"newlocation", :value=>"true"}
								%button.btn.btn-default.navbar-btn{ :type=>"submit"}
									%i.mdi.mdi-lg.mdi-cloud-upload
									Publica tu Locación

					-if current_user
						%ul.nav.navbar-nav.current-user
							%li.dropdown
								%a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
									.user-avatar.inline
										%i.mdi.mdi-account.mdi-lg
										- if(current_user.notifications("location")+current_user.notifications("booking"))>0
											.badge
												= current_user.notifications("location")+current_user.notifications("booking")
									%span.caret
								%ul.dropdown-menu
									%li.dropdown-header
										Hola
										%strong #{current_user.first_name}
									%li
										%a{:href => "/users/"+current_user.id.to_s}
											%i.mdi.mdi-lg.mdi-account
											Mi Perfil
											- if current_user.notifications("location")>0
												.badge
													=current_user.notifications("location")
									%li
										%a{:href => "/bookings"}
											%i.mdi.mdi-lg.mdi-calendar-multiple
											Mis Reservas
											- if current_user.notifications("booking")>0
												.badge
													=current_user.notifications("booking")

									%li.divider
									%li
										%a{:href => "/logout"}
											%i.mdi.mdi-lg.mdi-close
											Salir