config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", confirmations: 'users/confirmations'}
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
	resources :locations do
	  get :autocomplete_tag_name, :on => :collection
	  member do
 	 		get 'request_removal'
  	end
	end

	root 'welcome#index'

		get '/about' => 'pages#about'
		get '/contacto' => 'pages#contact', as: 'contact'
		post '/contacto' => 'pages#contact'
		get '/faq' => 'pages#faq'
		get '/terminos-y-condiciones' => 'pages#terms-and-conditions', as: 'terms_conditions'
		get '/gracias' => 'pages#thanks'
		get '/nueva_locacion' => 'pages#new_location'
		get '/signup' => 'users#new', as: 'new_session'
		post '/users/new' => 'users#create'
	  get 'request_annulation/:id' => 'users#request_annulation', as: 'user_annulation'
		get '/login' => 'sessions#new'
		post '/login' => 'sessions#create'
		get '/logout' => 'sessions#destroy'
		get '/help/password' => 'sessions#requestpasswordupdate'
		post '/help/password' => 'sessions#requestpasswordupdate'
		get '/help/updatepassword/:code' => 'sessions#updatepassword', as: 'update_password'
		post '/help/updatepassword/:code' => 'sessions#updatepassword'
	  get 'location/:id/show_modal' => 'locations#request_removal', as: 'delete_location_modal'
	  get 'location/:id/request_del' => 'locations#delete_request', as: 'location_delete'
		resources :users, except: [:index, :edit, :update] do
			collection do
				get :edit
			end
		end
		patch '/users/update' => 'users#update'
		get '/set_locale/' => 'users#set_locale'

		get 'bookings/new' => 'bookings#new'
		get 'bookings/:id/edit', to: 'bookings#edit', as: 'edit_booking'
	  post 'bookings/:id/edit', to: 'bookings#update'
		post 'bookings/price' => 'bookings#price'
		get 'bookings/:code' => 'bookings#show', as: 'booking'
		get 'bookings/:code/payment/confirm' => "bookings#confirmpayment"
		get 'bookings/:code/accept' => 'bookings#accept', as: 'booking_accept'
		get 'bookings/:code/cancel' => 'bookings#cancel', as: 'booking_cancel'
		get 'bookings/:code/delete' => 'bookings#delete'
		delete "bookings/:id" => "bookings#destroy"
		post 'bookings/:code/comment' => 'bookings#comment'
		post 'bookings/create'=> 'bookings#create'
		get "bookings" => "bookings#index"
	  get 'booking/:id/cancel_modal' => "bookings#cancel_modal", as: 'cancel_booking'
	  get 'booking/:id/cancel' => 'bookings#cancel_booking', as: 'booking_cancelled'

		get 'locations/:id/approve' => 'locations#approve', as: 'approve_location'
		get 'locations/:id/archive' => 'locations#archive'
		delete 'locations/:id/destroy' => 'locations#destroy'
		get 'locations/:id/re_send_reject_email' => 'locations#re_send_reject_email'
		post 'locations/:id/frontpage' => 'locations#frontpage'
		get 'locations/:id/show_archive_modal' => 'locations#show_archive_modal'
		get 'locations/:id/show_contact_modal' => 'locations#show_contact_modal'
		put "locations/:id/feature_image" => "locations#feature_image"
		match "upload/:location" => "attachments#create", via: [:post,:patch]
		get "attachments/:id/destroy" => "attachments#destroy"
	  get 'users/:id/delete_modal' => 'users#request_delete', as: 'delete_modal'
	  get "uploads/:id/destroy" => "uploads#destroy"

		get '/admin/' => redirect('/admin/locations')
		get '/admin/collections' => 'collections#admin'
		get '/admin/locations' => 'locations#admin'
		get '/admin/users' => 'users#admin'
		get '/admin/bookings' => 'bookings#admin'

		resources :bookings
		resources :collections
		resources :locations

	resources :confs, only: [:index] do
    collection do
      get :edit
      post :update
    end
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
	require 'money'
	require 'money/bank/google_currency'
	Money.default_bank = Money::Bank::GoogleCurrency.new
	belongs_to :user
	belongs_to :collection

	has_many :bookings, dependent: :destroy
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	has_many :attachments, dependent: :destroy
	has_many :uploads, dependent: :destroy

	accepts_nested_attributes_for :uploads, allow_destroy: true

	enum status: [ :archived, :draft, :submitted, :approved ]

	#SEARCH
	include PgSearch
  	multisearchable :against => [:title, :description, :city, :county, :services, :extras]
  	pg_search_scope :custom_search, :against => [:title, :description, :city, :county, :services, :extras], :associated_against => {:tags => [:name]}, :using => { :tsearch => {:prefix => true} }

	acts_as_paranoid

	#AFTER
	before_create :set_draft_status
	attr_accessor :tag_names
	after_save :assign_tags

	def statusnames
		["Archivada","Borrador","Esperando Aprobación","Publicada"]
	end

	def labels
		["label-danger","label-default","label-info","label-success"]
	end

	def statuslabel
		return labels[self.read_attribute('status')]
	end

	def statusname
		return statusnames[self.read_attribute('status')]
	end

	def savephoto(upload_id)
		upload=Upload.find(upload_id)
		if upload
		  upload.update_columns(location_id: self.id)
		  upload.save
		  true
		else
		  false
		end
	end

	def tag_names
    @tag_names || tags.map(&:name).join(', ')
    #@tag_names || tags.map{ |tag|  link_to tag.name, '/location' }
	end

	def addtag(word)
		name=word.gsub(/[^0-9a-z ]/i, '').downcase
		tag=Tag.where(:name=>name).first_or_create
		tagging=Tagging.where(:tag_id=>tag.id,:location_id=>self.id).first_or_create
	end

	def approve
		if (self.status=="submitted"||self.status=="archived")
			self.update_attribute(:status,"approved")
			true
		else
			false
		end
	end

	def archive
		self.update_attribute(:status,"archived")
		true
	end

	def submit
		if self.user && self.status=="draft"
			self.update_attribute(:status,"submitted")
			true
		else
			false
		end
	end

	def thumbnail(w,h)
		upload = self.main_attachment
		if upload != nil
			upload.image.url(:thumb)
		else
			"/location-missing.jpg"
		end
	end

	def thumbnail_old(w,h)
		attachment = self.main_attachment
		if attachment != nil
			attachment.thumbnail(w,h)
		else
			"/location-missing.jpg"
		end
	end

	def main_attachment
		if self.main_attachment_id && Upload.find_by_id(self.main_attachment_id) != nil
			Upload.find_by_id(self.main_attachment_id)
		elsif self.uploads.count > 0
			self.uploads.last
		else
			nil
		end
	end

	def main_attachment_url(style= nil)
		return "/location-missing.jpg" unless main_attachment
		return main_attachment.image.url unless style
		begin
			return main_attachment.image.url(style.to_sym)
		rescue
			return "/location-missing.jpg"
		end
	end

	def user_full_name
		if self.user
			user.try(:full_name)
		else
			nil
		end
	end

	def totalprice
		if !self.fee.nil? && !self.price.nil?
			self.price+self.fee
		else
			self.price
		end
	end

	def price_with_fee
		currency_type = I18n.locale == :es ? :CLP : :USD
		return 0 unless self.price
		price_result = self.price+(self.price*0.15)
		money = price_result.to_money(:CLP)
		converted_money = money.exchange_to(currency_type.to_sym)
		return converted_money
	end

	def has_other_extras?
		extras.select{|e| e == "Otro"}.length > 0
	end

	def has_other_services?
		services.select{|e| e == "Otro"}.length > 0
	end

	def has_date_range_available?(start_time, end_time)
		# Locaciones que aún esten siendo utilizadas cuando comienza la reserva
		self.bookings.where("status>2").where("start_time <= ? AND end_time >=?", end_time, start_time).blank?
	end

	def convert_attachments_to_uploads
		self.attachments.each do |att|
			begin
				self.uploads.create(image: open(att.url))
			rescue => e
				puts "#{att.url} failed"
			end
		end
	end

	def is_new_record?
		status == "draft"
	end

	private
		def set_draft_status
			# status codes:
			# 0=archived,1=draft,2=submitted,3=approved
			self.status="draft"
		end
		def assign_tags
			#@tag_names.split("/\s*,\s*/").map do |name|
			if @tag_names
				self.tags=[]
				@tag_names.split(/, ?/).each do |name|
					self.addtag(name)
					#Tag.find_or_create_by(name: name) if name.present?
				end
			end
		end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:frontpage, :feature_image]
  autocomplete :tag, :name
  before_action :set_location, only: [:show, :edit, :update, :destroy, :archive, :approve, :front_page, :delete_request]
  load_and_authorize_resource

  # GET /locations
  def index
    if params[:s]
      @locations=Location.where(:status=>3).custom_search(params[:s]).order(created_at: :desc)
    elsif params[:collection]
      @locations = Location.where(:status=>3).where(:collection_id=>params[:collection]).order(created_at: :desc)
    else
      @locations = Location.where(:status=>3).order(created_at: :desc)
    end
  end

  def admin
    REDIS.set("location_notifications_"+current_user.id.to_s,"0")
    @approved=Location.approved.order("created_at DESC")
    @submitted=Location.submitted.order("created_at DESC")
    @drafts=Location.draft.order("created_at DESC")
    @archived=Location.archived.order("created_at DESC")
    unless current_user.status=="admin"
      @approved=@approved.where(:user_id=>current_user.id)
      @submitted=@submitted.where(:user_id=>current_user.id)
      @drafts=@drafts.where(:user_id=>current_user.id)
    end
    @totalcount=@approved.count
  end

  # GET /locations/1
  def show
    #if @location.status == "approved" || (current_user&&current_user.status=="admin") || @location.user == current_user
      case @location.status
      when "submitted"
        flash.now[:notice] = "Esta locación está esperando aprobación y en algunas horas mas será publicada."
      when "archived"
        flash.now[:error] = "Tu locación no ha sido aprobada debido a los siguientes problemas: "
      end
      user=current_user
      respond_to :html
  end

  def frontpage
    @location = Location.find(params[:id])
    if @location.update_attributes(:front_page => params[:front_page])
      # ... update successful
      render :text => "YES"
    else
      # ... update failed
      render :text => "NO"
    end
  end

  # GET /locations/new
  def new
    @location = Location.new
    @location.user_id=current_user.id
    #to improve
    @location.save
    redirect_to edit_location_path(@location.id, newlocation: true)
  end

  # GET /locations/1/edit
  def edit
  end

  def show_archive_modal
  end

  def show_contact_modal
  end

  def re_send_reject_email
    if @location.user
      UserMailer.location_problem(@location).deliver
    end
  end

  def create
    @location = current_user.locations.new(location_params)
    respond_to do |format|
      if @location.save
        if params[:images]
          params[:images].each do |image|
            @location.uploads.create(image: image)
          end
        end
        UserMailer.location_submitted(@location).deliver
        AdminMailer.location_submitted_admin(@location).deliver
        @location.update_attribute("status", 2)
        format.html { redirect_to(location_path(@location, :open=>@modal), :notice => 'La locación fue creada con exito.') }
        format.js
      else
        format.html { render :action => "new" }
        format.js
      end
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      @location.submit
      if params[:images]
        #===== The magic is here ;)
        params[:images].each do |image|
          @location.uploads.create(image: image)
        end
      elsif params[:new_record]
        AdminMailer.location_submitted_admin(@location).deliver
        UserMailer.location_submitted(@location).deliver
      end
      respond_to do |format|
        format.json { render json: @location.uploads.last.append_file_json, status: :ok }
        format.html { redirect_to @location }
      end
    else
      render :edit
    end
  end

  def approve
    @location.approve
    @location.user.notify("location")
    UserMailer.location_approved(@location).deliver
    redirect_to "/admin/locations", notice: "La locación #{@location.title} fue aprobada con exito."
  end

  def archive
    @location.archive
    @location.update_attribute(:reject_reason, params[:reject_reason])
    if @location.user
      UserMailer.location_problem(@location).deliver
    end
    redirect_to '/admin/locations', notice: "La locación #{@location.title} fue archivada con exito."
  end

  def destroy
    if @location.destroy
      if params[:from_user]
        user_id = params[:from_user]
        redirect_path = "/users/#{user_id}"
      else
        redirect_path = "/admin/locations"
      end
      redirect_to redirect_path, notice: "La locación #{@location.title} fue destruida con exito."
    end
  end

  def feature_image
    @location.update_attribute(:main_attachment_id,params[:attachment_id])
    respond_to do |format|
      format.json { render json: @location, status: :ok }
    end
  end

  def request_removal
    @location = Location.find_by(id: params[:id])
  end

  def delete_request
    AdminMailer.request_location_removal_admin(@location, params[:reject_reason]).deliver_now
    UserMailer.request_location_removal_owner(@location, params[:reject_reason]).deliver_now
    redirect_to "/users/#{@location.user.id}", flash: {notice: "Se ha notificado al administrador para eliminar la locación #{@location.title}"}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def location_params
      #params[:location][:tag_names] ||= []
      #, { :tag_names=>[] }
      params.require(:location).permit(:title,
                                      :days,
                                      :city,
                                      :type_id,
                                      :price,
                                      :fee,
                                      :description,
                                      :address,
                                      :lat,
                                      :lng,
                                      :county,
                                      :collection_id,
                                      :front_page,
                                      :upload,
                                      :tag_names,
                                      :other_extras_comment,
                                      :other_services_comment,
                                      :uploads,
                                      { :uploads_attributes=>[ :_destroy, :id, :image ] },
                                      { :services=>[] },
                                      { :extras=>[] }
                                      )
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_archive_modal.html.haml
#archiveModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Archivar Locación
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = form_tag("/locations/#{@location.id}/archive", method: "get") do
          .form-group
            = label_tag(:reject_reason, "Motivo de rechazo:")
            = text_area_tag 'reject_reason', nil, class: 'form-control'
          .modal-footer
            = submit_tag 'Archivar', :class=>"btn btn-danger"

app/views/locations/_errors.html.haml
- if @location.errors.any?
	.errors
		%h3
			= pluralize(@location.errors.count, 'error')
			prohibited this location from being saved:
		%ul
			- @location.errors.full_messages.each do |message|
				%li= message

app/views/locations/_location.html.haml
.col-sm-6.col-md-4
	.thumbnail.thumbnail-reset.location-preview
		.image
			.badge-price
				%span
					= number_to_currency(location.price_with_fee, :unit => "$", :precision => 0)
				%span.currency
					= locale == :es ? "CLP" : "USD"
			= link_to location_path(location) do
				%img{:src=>location.main_attachment_url(:thumb), :onError=>"this.onerror=null;this.src='/missing.png';"}

		.caption
			%h3.title
				= link_to location.title, location_path(location)
			-if description && description==true
				%p.desc
					= location.description
			-#%p= link_to "ver locacion", location, :class => "btn btn-primary"
				= link_to 'editar', edit_location_path(location)
				= link_to 'eliminar', location, method: :delete, data: { confirm: '¿Seguro que quieres eliminar esta locación?' }
				= link_to "Show all bookings", location_bookings_path(location)
				= link_to "Delete", location_path(location), data: { confirm: 'Are you sure?' }, method: :delete
				= link_to "Edit", edit_location_path(location)
				= link_to "Add booking", new_location_booking_path(location)

app/views/locations/_upload.html.erb
<li><%=image_tag(thumb)%></li>

app/views/locations/admin.html.haml
%section.main-content
  .container
    .row
      = flash_messages
      =render 'shared/adminmenu'
      .col-md-12
        %h1 #{@totalcount} locaciones aprobadas
        %ul.nav.nav-tabs
          %li.nav-item
            %a.nav-link.active{"data-toggle" => "pill", :href => "#approved"} Esperando Aprobación
          %li.nav-item
            %a.nav-link{"data-toggle" => "pill", :href => "#published"} Publicadas
          %li.nav-item
            %a.nav-link{"data-toggle" => "pill", :href => "#archived"} Archivadas
        .tab-content.mt-4
          #approved.tab-pane.active
            / %h3 Esperando aprobación
            %table.table.table-striped
              %thead
                %tr
                  %th Nombre
                  %th Dueño
                  %th Descripcion
                  %th{:colspan => "3"}
              %tbody
                - @submitted.each do |location|
                  %tr
                    %td= link_to location.title, "/locations/#{location.id}"
                    %td= link_to location.user_full_name, '/users/'+location.user.id.to_s
                    %td= location.description
                    %td= location.statusname
                    %td
                      = number_to_currency(location.totalprice, :unit => "$", :precision => 0)
                    %td= link_to 'Editar', "/locations/#{location.id}/edit", :class=>"btn btn-info"
                    - if location.status=="submitted" && (can? :approve, Location)
                      %td= link_to 'Aprobar', "/locations/#{location.id}/approve", :class=>"btn btn-success"
                    - if location.status=="archived"
                      %td= link_to 'Borrar', "/locations/#{location.id}/destroy", :method => :delete, :class=>"btn btn-danger"
                    -else
                      %td= link_to 'Archivar', "/locations/#{location.id}/show_archive_modal", :class=>"btn btn-danger", :remote => true
            %br/
            = link_to 'Nueva locacion', new_location_path, :class=>"btn btn-info"
          #published.tab-pane.fade
            / %h3 Aprobadas
            %table.table.table-striped
              %thead
                %tr
                  %th Nombre
                  %th Dueño
                  %th Descripcion
                  %th{:colspan => "3"}
              %tbody
                - @approved.each do |location|
                  %tr
                    %td= link_to location.title, "/locations/#{location.id}"
                    %td= link_to location.user_full_name, '/users/'+location.user.id.to_s
                    %td= location.description
                    %td= location.statusname
                    %td= number_to_currency(location.totalprice, :unit => "$", :precision => 0)
                    %td= link_to 'Editar', "/locations/#{location.id}/edit", :class=>"btn btn-info"
                    - if location.status!="archived"
                      %td= link_to 'Archivar', "/locations/#{location.id}/show_archive_modal", :class=>"btn btn-danger", :remote => true
          #archived.tab-pane.fade
            / %h3 Borradores
            %table.table.table-striped
              %thead
                %tr
                  %th Nombre
                  %th Dueño
                  %th Descripcion
                  %th{:colspan => "4"}
              %tbody
                - @archived.each do |location|
                  %tr
                    %td= link_to location.title, "/locations/#{location.id}"
                    %td= link_to location.user_full_name, '/users/'+location.user.id.to_s
                    %td= location.description
                    %td= location.statusname
                    %td= number_to_currency(location.totalprice, :unit => "$", :precision => 0)
                    %td= link_to 'Editar', "/locations/#{location.id}/edit", :class=>"btn btn-info"
                    - if location.status!="approved"
                      %td= link_to 'Aprobar', "/locations/#{location.id}/approve", :class=>"btn btn-success"
                    %td= link_to 'Destruir', "/locations/#{location.id}/destroy", :method => :delete, :class=>"btn btn-danger"
                    %td= link_to 'Notificar Rechazo', "/locations/#{location.id}/show_archive_modal", :class=>"btn btn-danger", :remote => true
#archiveModalHolder

app/views/locations/edit.html.haml
- content_for :body_class, "edit-location"
%section.main-content
	.container
		= render 'shared/breadcrumb'
		.row
			= render 'form'
		- if current_user.status == "admin"
			= link_to 'Destruir', "/locations/#{@location.id}", method: :delete, :class=>"btn btn-danger btn-block", data: { confirm: 'Are you sure?' }

app/views/locations/new.html.haml
- content_for :body_class, "new-location"
%section.main-content
	.container
		= render 'shared/breadcrumb'
		.row
			= render 'form'

app/views/locations/request_removal.js.erb
$("#locationModalHolder").html("<%= j raw(render 'users/location_delete_modal', location: @location) %>")
$("#locationModal").modal()

app/views/locations/show.html.haml
- content_for :body_class, "special-layout location-single"

%section.main-content.location
	.location-header{ :style=>"background-image:url(#{@location.main_attachment_url}) !important" }
		.container
			.location-title
				%h1
					= @location.title
					%small= @location.city
			%aside.location-booking-info
				- if @location.price_with_fee > 0
					.price
						= number_to_currency(@location.price_with_fee, :unit => "$", :precision => 0, :format => "%u%n")
						%small CLP
					%small.availability
						=t('location.price_by_day')
						/ Días: #{@location.days}
				-if current_user && @location.bookings.where('user_id = :me AND status != :cancelled', me: current_user.id, cancelled: 0).any? && @location.price_with_fee > 0
					.booking.padding-top
						%a.btn.btn-primary.btn-block.btn-lg{:href => "/bookings/"+@location.bookings.where(:user_id=>current_user.id).last.code}
							%i.mdi.mdi-lg.mdi-calendar-clock
							=t('actions.see_booking')
					%a{ :href => "/bookings/new?id="+@location.id.to_s}
						=t('actions.book_again')
				-else
					.booking.pt-3
						- if (can? :update, @location)
							%a.btn.btn-primary.btn-block.btn-lg{:href => "/locations/"+@location.id.to_s+"/edit"}
								%i.mdi.mdi-lg.mdi-pencil
								=t('actions.edit', model: t('general.location'))
						- elsif @location.status=="approved"
							%a.btn.btn-primary.btn-block.btn-lg{:href => "/bookings/new?id="+@location.id.to_s}
								%i.mdi.mdi-lg.mdi-calendar-clock
								=t('actions.book', model: t('general.location'))
						.booking-contact
							=t('general.questions')
							%a.btn.btn-link.btn-sm.p-0{:href => "/contacto?subject=Consulta por Locación "+@location.id.to_s, :role => "button", :style => "z-index: 99999999;position: relative;"}
								%i.mdi.mdi-lg.mdi-email-outline
								=t('general.contact_us')
	.container
		.row.location-content
			.col-md-7
				- if flash[:notice]
					.mt-3.alert.alert-success{:role => "alert"}
						%button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
							%span{"aria-hidden" => "true"} ×
						= flash[:notice]
				- if flash[:error]
					%br
					.alert.alert-danger.reject-alert{:role => "alert"}
						= flash[:error]
						%strong
							= @location.reject_reason if @location.reject_reason
						= t('extras.you_can')
						= link_to t('actions.edit', model: t('general.location')), edit_location_path(@location.id)
						= t('extras.or')
						= link_to t('general.contact_us'),"/locations/#{@location.id}/show_contact_modal", remote: true
				- if flash[:warning]
					.mt-3.alert.alert-warning{:role => "alert"}
						%button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
							%span{"aria-hidden" => "true"} ×
						= flash[:warning]
				.content-box.description
					%h3
						= t('general.description')
					%p= @location.description
				.content-box.details
					%h3
						= t('general.details')
					.table-responsive
						%table.table.table-hover
							%tbody
								-if @location.type_id
									%tr.row.my-2
										%th.col-md-5=t('location.type')
										%td.col-md-7 #{@location.type_id}
								-if @location.services
									%tr.row.my-2
										%th.col-md-5=t('location.services')
										%td.col-md-7 #{raw(@location.services.join(", ").split(/\s*,\s*/).map{ |service| raw(link_to(service, '/locations?s='+service.html_safe)) }.join(', '))} #{(@location.has_other_services? ? ("(" + @location.other_services_comment.to_s + ")") : '')}
								-if @location.extras
									%tr.row.my-2
										%th.col-md-5=t('location.extras')
										%td.col-md-7 #{raw(@location.extras.join(", ").split(/\s*,\s*/).map{ |extra| raw(link_to(extra, '/locations?s='+extra.html_safe)) }.join(', '))} #{(@location.has_other_extras? ? ("(" + @location.other_extras_comment.to_s + ")") : '')}
								-if @location.tag_names
									%tr.row.my-2
										%th.col-md-5 Tags
										%td.col-md-7 #{raw(@location.tag_names.split(/\s*,\s*/).map{ |tag| raw(link_to(tag, '/locations?s='+tag.html_safe)) }.join(', '))}
			.col-md-5.text-right
				-if @location.lat && @location.lng
					.content-box.address
						%h3.address-title
							=t('location.latitude')
						.map#map
							:javascript
								var map;
								$(document).ready(function(){
									map = new google.maps.Map(document.getElementById('map'), {
										center: {lat: #{@location.lat}, lng: #{@location.lng}},
										zoom: 14,
										disableDefaultUI: true,
										scrollwheel: false,
										draggable: false
									});
								});
					%small Ubicación aproximada, reserva para obtener más información.
			-if @location.uploads.count>0
				.col-md-12
					.content-box.gallery
						%h3.gallery-title
							=t('general.image_gallery')
						%ul.gallery-list
							-@location.uploads.each do |upload|
								%li.gallery-slot
									%a.gallery-link{:href => upload.image.url, "data-gallery" => ""}
										=image_tag(upload.image.url(:thumb), :class=>"gallery-img")	
							-#%li
								%a{:href => "/missing.png", "data-gallery" => ""}
									=image_tag "missing.png"
			-if current_user && (current_user.status=="admin" || current_user.status=="moderator")
				.col-md-12.padding
					- if @location.status != "approved"
						= link_to t('general.approve'), "/locations/#{@location.id}/approve", :class=>"btn btn-success"
					- if @location.status != "archived"
						= link_to t('general.archive'), "/locations/#{@location.id}/show_archive_modal", :class=>"btn btn-danger", :remote => true
				.col-md-12.padding
					%ul.list-inline
						%li.list-inline-item
							= link_to locations_path do
								%i.mdi.mdi-arrow-left
								=t('actions.go_back')
						%li.list-inline-item
							= link_to edit_location_path(@location) do
								%i.mdi.mdi-pencil
								= link_to t('actions.edit', model: t('general.location'))
						-if @location.attachments.count>0
							%li.list-inline-item
								%i.mdi.mdi-home
								= check_box_tag "locations[front_page]", @location.id, !!(@location.front_page)
								=t('actions.feature_in_home')
						%li.list-inline-item
							=form_for(@location, :html => {:class=>"form-inline"}) do |f|
								.form-group
									=f.label t('general.collection')
									=f.collection_select(:collection_id, Collection.all, :id, :name, {}, {:class=> "form-control"})
								=f.submit t('actions.add_to_collection'), :class=> "btn btn-primary"
					-if @location.attachments.count>0
						:javascript
							$("#locations_front_page").bind('change', function(){
								if (this.checked){
									$.ajax({
										url: '/locations/'+this.value+'/frontpage',
										type: 'POST',
										data: {"front_page": true}
									});
								}
								else {
									$.ajax({
										url: '/locations/'+this.value+'/frontpage',
										type: 'POST',
										data: {"front_page": false}
									});
								}
							});
#archiveModalHolder
#contactModalHolder